# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 389350fefe35c098887bd9bfd51b012e0377939b88fde29bf13047551a77c03f8271afb173f1a53842b8698ff4c2bb987f7196a8f13396557a39afcd1db8cf99

test:
  secret_key_base: ab6580711552cf989c909f1b8a474790dc487b1540f8fc6e4b0cdd9915f322bd49e84b4974ad92edcc03e6e88adbc109edd38265bbee876d8ffef738bf590742

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
